- name: PING
  hosts: web
  tasks: # task=module=collection
  - name: ping the server
    ansible.builtin.ping:

- name: Install ntpdate
  ansible.builtin.package:
    name: ntpdate
    state: present